### ISSUE TITLE
création de la vue validation

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/gn_module_validation#1]
Créer une vue validation basée sur la synthèse.

**Comment by sig-pnrnm** [comment]
Un point important de cette vue sera, quand le protocole source permet d'ajouter un média à la donnée (photo dans la grande majorité des cas, éventuellement audio ou vidéo ??), d'afficher ce média qui est un élément clé de la validation.

**Comment by camillemonchicourt** [comment]
Oui c'est noté dans le ticket général sur le module de Validation : https://github.com/PnX-SI/GeoNature/issues/181#issuecomment-358240295

Pour le moment la vue se base sur ce qui est présent actuellement dans GeoNature.

Commits liés : 
- https://github.com/PnX-SI/gn_module_validation/commit/887f389c354b4ca08057a5a4f1172fdb4b2e9be3
- https://github.com/PnX-SI/gn_module_validation/commit/6df855d817dc86657cd3f8a4b4e2fca4a8238cd4
- https://github.com/PnX-SI/gn_module_validation/commit/bad5c783ed7d8afbce1c3cd8c12d36afb0c1bc1a
