### ISSUE TITLE
Vue liste : ajouter code couleur validation

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/gn_module_validation#10]
Dans la vue des données à valider, le statut de validation est visible.
Avoir une vision du statut sous forme de codes couleurs serait plus ergonomique (voire même en enlevant le texte, et en ne l'affichant qu'au survol du picto (tooltip), ce qui permet de gagner de l'espace pour les autres colonnes
![validation](https://user-images.githubusercontent.com/26482054/48711215-ecb65300-ec0a-11e8-9ffe-37ec85782d46.png)

**Comment by camillemonchicourt** [comment]
Pourquoi pas mais ça ne va pas dans le sens de baser les statuts de validation de manière générique sur la nomenclature correspondante : https://github.com/PnX-SI/gn_module_validation/issues/7#issuecomment-439829831

**Comment by sig-pnrnm** [comment]
A moins de stocker, dans la nomenclature, l'info relative au code couleur correspondant aux différentes valeurs ?

Ce sont ici les 5 valeurs définies par le standard, qui certes peu bouger, mais qui semble quand même avoir déjà fait l'objet de pas mal de discussions.

Si des structures souhaitent ajouter des statuts de validation, elles pourront lui attribuer un code couleur spécifique.

**Comment by sig-pnrnm** [comment]
Ces codes couleurs ont d'ailleurs été repris dans le formulaire : 
![validation_form](https://user-images.githubusercontent.com/26482054/48714952-23dd3200-ec14-11e8-89c0-2b440ee4c028.png)

**Comment by camillemonchicourt** [comment]
Oui les valeurs et les couleurs sont en dur dans le code, ce qui n'est pas souhaitable. 

La table de stockage des nomenclatures est globale (même au-delà de GeoNature) et générique et ne prévoit pas de champs spécifiques pour stocker des couleurs ou autre : https://github.com/PnX-SI/Nomenclature-api-module/blob/master/data/nomenclatures.sql#L246

Si on veut des couleurs pour chaque valeur, on pourrait les lister dans la conf du module Validation en attribuant une couleur pour chaque Nomenclature de type ``STATUT_VALID`` en lien avec son ``cd_nomenclature`` : https://github.com/PnX-SI/Nomenclature-api-module/blob/master/data/data_nomenclatures.sql#L442-L447

Cela permettrait de ne pas mettre les valeurs en dur dans le code, de l'adapter si la nomenclature SINP évolue ou si certains souhaitent l'adapter.

**Comment by camillemonchicourt** [comment]
Ou idéalement faire une table générique au niveau des nomenclatures qui permet de gérer de manière globale des infos associées aux nomenclatures (couleur, picto....).

En attendant on le fait en CONF au niveau du module.

**Comment by sig-pnrnm** [comment]
Pour un rendu très simple en CSS avec différenciation des validation auto / manuelles : 
https://github.com/PnX-SI/gn_module_validation/issues/13#issuecomment-441009821
(ce n'est qu'une proposition bien entendu !)

**Comment by camillemonchicourt** [comment]
Couleurs intégrés dans la liste et couleurs définies dans la conf du module (conf_schema_toml.py)
