### ISSUE TITLE
Formulaire de validation : afficher la définition

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/gn_module_validation#11]
Dans le formulaire de validation, il faudrait rendre accessible la définition pour chaque statut de validation.
Celle-ci est bien stockée dans la table nomenclature.
Afin de conserver un formulaire le plus sobre et léger possible, cette définition pourrait n'être affichée qu'à la demande ("tooltip" ou petit "+" à côté de la valeur)

**Comment by camillemonchicourt** [comment]
Oui, voir https://github.com/PnX-SI/gn_module_validation/issues/7#issuecomment-434236469

**Comment by orovellotti** [comment]
Ajouter Bouton "Voir les définition des status" sur la boite de dialogue avec les définitions et les codes couleurs (permet de ne par allourdir l'interface en n-eme usage)
