### ISSUE TITLE
Conserver (historiser) et afficher les précédents statuts de validation

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/gn_module_validation#12]
En lien avec https://github.com/PnX-SI/GeoNature/issues/520

Il est important d'avoir une visibilité des précédents statuts de validations d'une occurence, et par qui et quand ils ont été attribués.

**Comment by camillemonchicourt** [comment]
Oui ça sera le cas dans la fiche détail d'une Occurrence.

**Comment by sig-pnrnm** [comment]
Ok, du coup il sera vraiment important d'avoir accessible, au sein du module validation, l'ensemble de l'historique du circuit de validation d'une occurence, avec affichage de "qui à fait quoi et quand".

Une vue sous forme de "journal".

**Comment by gildeluermoz** [comment]
Qui est l'auteur du premier statut de validation automatique = en attente de validation ?
Digitiser ?

**Comment by gildeluermoz** [comment]
Et si "dévalidation" automatique, comme envisagé en cas de modification d'une observation, il faut aussi un auteur.

**Comment by gildeluermoz** [comment]
Cela rejoint la notion de validation auto ou manuelle. Ce statut est peut à ajouter dans la table t_validations ainsi que dans l'interface.

**Comment by DonovanMaillard** [comment]
En attente de validation et dévalidation = pas d'auteur à mon sens (personne n'a attribué le statut). 

Donc je verrais plutôt soit une valeur par défaut ("attribué automatiquement"), ce qui me semble le plus clair, soit NA.

Quant au mode de validatio' automatique ou manuelle...  Est ce l'un ou l'autre, ou l'un puis l'autre, comment ça se passe en cas de conflit entre les deux...   Ça amène pas mal de question, qui a la limite concerne chaque utilisateur et sa politique en interne, mais à voir comment tout ça peut d'articuler niveau interface etc

**Comment by camillemonchicourt** [comment]
Pour rappel la première validation automatique insérée lors de la création de l'observation peut être autre chose que "En attente de validation". Cela dépend de la valeur par défaut définie dans la BDD dans la table des valeurs par défaut des nomenclatures.

En effet on pourrait indiquer "Attribué automatiquement" mais comme la clé étrangère est sur utilisateurs.t_roles ce n'est pas possible donc je ne mettrai rien car ce n'est pas l'observateur ni le digitiser.

Cette première validation est d'ailleurs liée à https://github.com/PnX-SI/GeoNature/issues/520 qui est à implémenter.

**Comment by sig-pnrnm** [comment]
> Cela rejoint la notion de validation auto ou manuelle. Ce statut est peut être à ajouter dans la table t_validations ainsi que dans l'interface.

C'est exactement ça !
J'étais passé à côté de cette notion du standard SINP, et en la découvrant la semaine dernière, ça a répondu à beaucoup de nos questions sur la validation.

Après, pour ce qui est de l'auteur des ces "validations automatiques", je ne connais pas encore ce que vous entendez par "digitizer", mais ce qui semblerait efficace, c'est un compte non nominatif associé à l'instance GeoNature.

> Quant au mode de validatio' automatique ou manuelle... Est ce l'un ou l'autre, ou l'un puis l'autre, comment ça se passe en cas de conflit entre les deux... Ça amène pas mal de question, qui a la limite concerne chaque utilisateur et sa politique en interne

Tout cela est décrit dans le standard Validation du SINP.
Les 2 notions doivent cohabiter !

**Comment by gildeluermoz** [comment]
Oui les validations s'empilent et l'une peut être attribuée par un mécanisme, automatique donc, et la suivante être manuelle. Les deux cohabitent, se succèdent et il n'est pas inutile que les validateurs disposent de cette info.

**Comment by camillemonchicourt** [comment]
Fait.
