### ISSUE TITLE
Validation automatique ou manuelle

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_validation#13]
Ajouter un booléen ``Manuel`` dans la table ``gn_commons.t_validations`` avec False par défaut.
Les validations saisies par l'interface passent ce champs à ``True``.

Ou inversement.

**Comment by camillemonchicourt** [comment]
Afficher cette information au niveau de l'historique des validation dans la fiche Détail d'une occurrence ne sera pas un problème. 
Cependant ça pourra être plus lourd au niveau de la liste des occurrences car actuellement le contenu de cette liste se base sur du contenu présent à plat dans la Synthèse. 
Hors l'information manuel/automatique sera à récupérer dans la table ``gn_commons.t_validations``

**Comment by gildeluermoz** [comment]
DONE : https://github.com/PnX-SI/GeoNature/commit/c5a92c297188fe05cef8744c766395ac786ea842

**Comment by camillemonchicourt** [comment]
OK, donc @JulienCorny, désormais quand tu insères une validation dans ``gn_commons.t_validations``, il faut que tu pousses FALSE dans ce champs.

**Comment by sig-pnrnm** [comment]
pour illustrer mon propos avec un CSS à l'arrache : 
https://jsfiddle.net/SIG_PNRNM/junb63re/
![statuts](https://user-images.githubusercontent.com/26482054/48901310-4c07a380-ee55-11e8-9a89-b5becfc78df6.png)

**Comment by sig-pnrnm** [comment]
Ou tout simplement avec un petit caractère : 
https://jsfiddle.net/SIG_PNRNM/junb63re/25/
![statuts2](https://user-images.githubusercontent.com/26482054/48901908-2bd8e400-ee57-11e8-811c-b3657b0fe412.png)

**Comment by camillemonchicourt** [comment]
Non on stocke à plat le dernier statut de validation d'une occurrence avec l'``id_nomenclature`` correspondant dans le champs de la table ``gn_synthese.synthese`` : https://github.com/PnX-SI/GeoNature/blob/develop/data/core/synthese.sql#L172

Pour récupérer l'info si le dernier statut de validation est manuel ou automatique, il faut retrouver cette info dans la table ``gn_commons.t_validations``. C'est pas idéal car tout le reste est à plat mais ça doit pas non plus plomber les performances. 

Pour l'affichage et les couleurs, je n'ai pas d'avis tant que c'est dynamique sur le contenu de la nomenclature et paramétrable au niveau de la conf du module.

**Comment by sig-pnrnm** [comment]
> Non on stocke à plat le dernier statut de validation d'une occurrence avec l'id_nomenclature correspondant 

et dans ce cas, ne pourrait-on pas imaginer de distinguer, dans les nomenclatures, les validations auto et manuelles ?
un `probable auto` et un `probable manuel` n'aurait pas le même `id_nomenclature`
Ca évite aussi d'ajouter le champ booleen `auto` (oui/non).

**Comment by camillemonchicourt** [comment]
On utilise les nomenclatures SINP pour bien pouvoir recoller avec les standards.
Pas souhaitable du coup.
Mieux vaut faire une jointure sur t_validations

**Comment by JulienCorny** [comment]
Bonjour,

C'est noté,  dynamique sur nomenclature et paramétrable. 
Pour l'affichage, je pencherais plus sur la 2eme solution, avec une lettre à l'intérieur, ça me semble plus intuitif que des signes dont l'utilisateur devra connaitre la signification, en plus du code couleurs.

**Comment by camillemonchicourt** [comment]
Oui

**Comment by gildeluermoz** [comment]
Pour le moment, les nomenclatures insérées dans `t_nomenclatures` ne font pas cette distinction. Faut-il le faire ?

**Comment by camillemonchicourt** [comment]
Ça serait dommage car du coup il n'y aurait plus de lien entre une Validation automatique et manuelle de même niveau (Probable par exemple), car elles auraient un ``id_nomenclature`` différent. 
Pour retrouver les occurrences de validation probable, il faudrait combiner 2 nomenclatures...

Pour les définitions, j'utiliserai celles de la validation manuelle dans la module de Validation puisque c'est ce qu'on y fait.

**Comment by sig-pnrnm** [comment]
> les nomenclatures insérées dans t_nomenclatures ne font pas cette distinction. Faut-il le faire ?

Selon moi, oui !

> Ça serait dommage car du coup il n'y aurait plus de lien entre une Validation automatique et manuelle de même niveau

Je ne trouve personnellement pas cela dommage : les définitions sont différentes, cela ne peut donc pas être le même `id_nomenclature` ?
Le lien pourra se faire via un autre champ de la table (`mnemonique` ou `label_*`).
Et pour ce qui est des interfaces, la correspondance sera "visuelle" (avec le code couleur).

> Pour les définitions, j'utiliserai celles de la validation manuelle dans la module de Validation puisque c'est ce qu'on y fait.

Là, je suis d'accord : c'est bien la fonction du module validation de notre commande.

**Comment by camillemonchicourt** [comment]
> Je ne trouve personnellement pas cela dommage : les définitions sont différentes, cela ne peut donc pas être le même id_nomenclature ?
> Le lien pourra se faire via un autre champ de la table (mnemonique ou label_*).
> Et pour ce qui est des interfaces, la correspondance sera "visuelle" (avec le code couleur).

Là je vois pas bien. L'``id_nomenclature`` est la clé primaire, donc 2 nomenclatures ne peuvent pas avoir le même id. Et ça va faire un truc pas super propre. 
On peut faire des nomenclatures de niveau 2 mais c'est un peu lourd et pas forcément mur. 

Je resterai vraiment sur une seule nomenclature, que ce soit manuel ou automatique. Et on peut retrouver cette info au niveau des enregistrements dans la table ``gn_commons.t_validations``.

**Comment by sig-pnrnm** [comment]
> L'id_nomenclature est la clé primaire, donc 2 nomenclatures ne peuvent pas avoir le même id

C'est bien ce que je dis, et c'est pourquoi je pense que cela doit être 2 id différents
Après, vous maîtrisez mieux que moi les fondamentaux de la structure de GN, donc je me plierai à votre décision ;)

**Comment by camillemonchicourt** [comment]
Affichage de l'info = OK. 
Champs booléen et même nomenclature actuellement.
