### ISSUE TITLE
Pouvoir envoyer email à observateur

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_validation#15]
Dans la fiche Détail, pouvoir envoyer un email aux observateurs de l'occurrence. 
Pour cela il faut récupérer l'email dans ``utilisateurs.t_roles`` pour pouvoir l'afficher en "mailto" quand disponible sur les champs observateurs.

**Comment by sig-pnrnm** [comment]
Je me permets de relancer l'issue car ce n'est pas actif sur la version de demo actuel.

**Comment by camillemonchicourt** [comment]
Fait.
