### ISSUE TITLE
Nombre d'observations sélectionnées incohérent

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/gn_module_validation#19]
Après avoir sélectionné 1 seule observation, l'ouverture du formulaire de validation indique que 2 données sont sélectionnées.
A l'attribution du statut, le message indique que 2 données ont été modifiées.
cf. capture d'écran : 
![validation_nb_obs](https://user-images.githubusercontent.com/26482054/52478926-3a59b080-2ba7-11e9-8c52-1b7ff0f1d36f.gif)

J'ai aussi eu un cas où ça m'a indiqué que 5 obs. étaient sélectionnées, alors qu'il n'y en avait aussi qu'une.

**Comment by sig-pnrnm** [comment]
Je viens de reproduire le problème en faisant une recherche après avoir sélectionné une observation.
Le problème venait du fait que la recherche ne déselectionnait pas une donnée précédemment sélectionnée (par erreur, car juste au clic).

Cela veut dire qu'on peut valider des données non visibles.

Il faudrait soit : 
- que le filtre de recherche demande si on doit conserver les observations sélectionnées
- que le filre de recherche déselectionne automatiquement les observations sélectionnées

**Comment by camillemonchicourt** [comment]
Je penche pour la deuxième solution pour éviter les questions.

**Comment by sig-pnrnm** [comment]
> Je penche pour la deuxième solution pour éviter les questions.

Oui, moi aussi.

Je précise, pour montrer encore plus le risque, que les données précédemment sélectionnées ne figurent plus dans la liste des données des x pages de résultats.
Il faut vraiment ne pas pouvoir valider des données absentes du résultat.

Par contre, la question se pose pour les données sélectionnées dans une autre page du résultat, sans avoir modifié le filtre de recherche.

Dans ce cas que fait-on :
- une alerte disant "attention, vous vous apprêtez à valider des données d'une autre page de résultat" ?
- on ne permet pas la validation de données d'une autre page ?
- ???

**Comment by camillemonchicourt** [comment]
Je crois pas trop aux messages et alertes. 

L'affichage du nombre de données concernées sert déjà à informer la quantité de données sélectionnées.

Il me semble important que tout sélectionner concerne bien toutes les pages de résultat si on veut valider des gros jeux de données.

**Comment by sig-pnrnm** [comment]
Ok, mais alors, sans ajouter d'alerte, juste afficher sur le formulaire de validation que des données ne sont pas sur la page visible : 
![validation_nb_obs2_alerte](https://user-images.githubusercontent.com/26482054/52486152-b1e50b00-2bba-11e9-9c8b-cfff198d170e.png)

**Comment by JulienCorny** [comment]
ok je vais corriger ce bug avec : 
- le filtre de recherche qui désélectionne automatiquement les observations sélectionnées
- et l'affichage dans le formulaire de validation du nombre d'observations sur les pages non visibles

**Comment by camillemonchicourt** [comment]
Fait
