### ISSUE TITLE
Bug sur la version develop-2.0.1

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/gn_module_validation#24]
Bonjour,

Basculant sur la version 2.0.1 de GN2, j'ai tenté l'installation du module validation. Parmi tous les manifest.toml, seul un ne rejette pas cette version de GN2. Je n'ai eu aucun message d'erreur à l'installation donc tout va bien (en théorie).
Mais une fois installé, lorsque j'ouvre la page du module, il s'affiche mais 1/ aucune donnée n'est affichée/listée et 2/ plus rien ne répond (pas même le bouton d'affichage du menu général).

Peut-être y a-t-il une manip' particulière pour les branches en développement? (je ne suis qu'un petit scarabée encore en apprentissage...)
Ma manip' (intégrer ce module sur la 2.0.1) est-elle prématurée?
C'est grave docteur?

**Comment by DonovanMaillard** [comment]
Bonjour, 

Sauf erreur, le module est encore en cours de développement. Selon les travaux en cours dessus, l'installation n'est peut être pas forcément possible (éléments qui ont disparu, changé de place ou autre ?). 

Il devrait arriver assez rapidement maintenant si je ne me trompe :)

**Comment by AudreyEnGuyane** [comment]
> l'installation n'est peut être pas forcément possible

En tous cas, j'ai pu l'installer :-D
j'avais pensé qu'il était fonctionnel comme sur la version démo.
Je vais le désinstaller et patienter un peu. N'hésitez pas à mettre un petit message sur cette conversation pour me faire signe! Je le testerai volontiers!

**Comment by DonovanMaillard** [comment]
il y aura une release, vous pouvez "watcher" le dépot pour avoir les mails avec les releases :)

**Comment by AudreyEnGuyane** [comment]
> il y aura une release, vous pouvez "watcher" le dépot pour avoir les mails avec les releases :)

Comme quoi, je suis VRAIMENT un petit scarabée... Mais petit bousier vient de "watcher"!
Merci Donovan!

**Comment by DonovanMaillard** [comment]
Pole invertébrés, le minimum est de guider les scarabées! :D mais surtout, on est tous le scarabée d'un autre! :)

**Comment by camillemonchicourt** [comment]
Oui attention à ne pas installer en production des modules qui ne sont pas sortis avec une Release.
Pour ce module, il y a une branche pour la compatibilité version 2 mais il faut encore la tester et corriger quelques petites choses

**Comment by AudreyEnGuyane** [comment]
Camille, le manifest de la compat-v2 mentionne 

> exclude_geonature_versions = [ '2.0.1', '2.0.3' ]
