### ISSUE TITLE
Ne pas utiliser les identifiants nomenclature dans les fichiers de conf mais les codes

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/gn_module_validation#30]
Dans le fichier `conf_schema_toml.py` les identifiants nomenclatures sont en dur (tableau STATUS_INFO) ce qui pose des soucis de compatibilité avec la nomenclature. Il faudrait mieux utiliser les codes nomenclatures (cd_nomenclature) qui eux sont censés être persistants entre les instances.

Par ailleurs il manque un test pour vérifier que l'identifiant retourné dans le jeux de données est bien dans la liste VALIDATION_CONFIG.STATUS_INFO

**Comment by camillemonchicourt** [comment]
Ah oui bien vu, surtout que ça a posé des problèmes à certains.
Ça serait encore plus simple et souple d'utiliser les CODES. 
Dans ce cas il faudrait ainsi un paramètre pour l'id ou le code du type de nomenclature, pour ne pas non plus le mettre en dur dans le code.

**Comment by camillemonchicourt** [comment]
Fait ici en même temps que de la  refactorisation du code : https://github.com/PnX-SI/GeoNature/commit/a9491f98bc81caa6bd2290655cdc5f025cde6b1c
