### ISSUE TITLE
Liste des données validables

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_validation#31]
Actuellement il semblerait que le module ne liste que les données qui ont un enregistrement correspondant dans ``gn_commons.t_validations``, donc principalement les données ayant été saisies dans Occtax, qui stockent une valeurs par défaut lors de leur insertion.

Par contre pour toutes les autres données insérées dans la Synthèse directement, elles ne remontent pas dans le module Validation. Hors, cela devrait être le cas, à partir du moment où elles ont un UUID_SINP. 

A voir aussi si on prend en compte un champ ``validable`` au niveau des sources ou JDD ?

**Comment by camillemonchicourt** [comment]
En lien avec https://github.com/PnX-SI/gn_module_validation/issues/16

**Comment by camillemonchicourt** [comment]
Le module liste désormais toutes les données présentes dans la Synthèse qui ont un UUID_SINP, pas seulement celles qui ont un enregistrement dans t_validations.
Fait dans GeoNature (https://github.com/PnX-SI/GeoNature/commit/f4265575b31a289f806508ee33acd20cbaa2717e), en même temps que d'autres compléments comme l'ajout des filtres géographiques sur la carto, la prise en compte des nomenclatures actives uniquement...

**Comment by DonovanMaillard** [comment]
Sans avoir un avis bien tranché (mais camille était intéressé pour un retour ici), le paramètre validable ou non ne me choquait pas dans la t_sources. En tous cas, il ne me semble pas plus adapté au niveau du jdd... 

La t_source est technique et est propre à chaque instance, comme le choix de pouvoir valider ou non les données. La t_datasets a plutôt vocation a stocker les infos sur l'acquisition des données en elles-mêmes, mais surtout à contenir des infos qui sont échangeables et pas propres à une instance. 

Du coup, pas d'avis tranché car globalement, le mettre au niveau du dataset ne pose pas de soucis particuliers. Mais niveau mcd, je trouvais plus cohérent d'avoir cette info au niveau de la t_source... 

Reste que la t_source n'est pas forcément remplie dans les imports manuels (rendre l'id_source obligatoire?). Le module validation rempli la t_source pour sa part, et on peut envisager un booléen au moment de l'import pour définir si les données sont validables ou non. Mais en soit, avec le fonctionnement actuel ca se choisit de la même manière dans le module MTD....

**Comment by sig-pnrnm** [comment]
> mais camille était intéressé pour un retour ici

Bien que commanditaire du développement initial, je dois vous avouer que je ne maitrise pas suffisamment les tenants et aboutissants du MCD pour avoir un avis sur la question (si jamais un avis de ma part était attendu :wink: )

**Comment by camillemonchicourt** [comment]
Fait dans meta.t_datasets : https://github.com/PnX-SI/GeoNature/commit/ebd4f7a51b8921c07501b146fe7bfa2f49e30075
