### ISSUE TITLE
Colonnes à afficher en front pour validation

### ISSUE THREAD

**Issue by JulienCorny** [PnX-SI/gn_module_validation#6]
Bonjour à tous, 

A votre avis, qu'est-ce qui serait le mieux pour l'affichage des colonnes en front pour le validateur :
Est-ce qu'on affiche les mêmes colonnes que pour le module synthèse (avec en plus bien sûr le statut de validation en première colonne) pour plus d'homogénéité (en mettant les noms latins à la place des noms vernaculaires pour plus de précision pour le spécialiste qui va valider les données?) ? ou est-ce qu'on affiche le nom de commune à la place du JDD comme prévu initialement dans la maquette? ou une autre combinaison de colonnes?

Taxon (en nom latin), date de l'observation, une info géo, nom de l'observateur me paraît pas mal pour un résumé rapide de l'observation non? l'utilisateur peut cliquer ensuite sur l'observation s'il veut plus de détails.

**Comment by DonovanMaillard** [comment]
Bonjour,

Parmi les infos qui me semblent importantes dans le résumé, ne pas oublier l'altitude. Pourquoi pas le stade mais ça c'est moins prioritaire je pense.

Je trouve que dans un context de validation la commune risque d'être plus utile que le jeu de données également. 

Donovan

**Comment by JulienCorny** [comment]
Bonjour,

Oui bonne idée pour l'altitude je pense. Est-ce qu'on peut estimer que l'info géo est donnée par le pointage de l'observation sur la carte (si le validateur veut plus d'infos géographiques il peut ensuite cliquer sur l'observation pour afficher les détails comme la commune)? ça permettrait d'alléger un peu la liste des données affichées

Julien

**Comment by camillemonchicourt** [comment]
Oui je pense que les infos géographiques sont visualisées sur la carte ou dans le détail d'une observation.

Il ne faut pas trop charger la liste car il y a peu de place et pour limiter le temps de chargement.

Faut voir ce qui a été fait sur la Synthèse mais à mon souvenir il est possible de paramétrer les champs affichés dans la liste.

**Comment by sig-pnrnm** [comment]
Ici à Normandie-Maine, l'info relative au JDD sera utile pour le validateur.
Mais comme la réponse semble variable d'une structure à l'autre (bien qu'on soit certainement tous d'accord pour que l'interface ne soit pas surchargée), l'idéal serait de pouvoir composer sa "vue de validation", en choisissant les champs à afficher / masquer (et en enregistrant ce "contexte" pour les prochaines validations.

**Comment by camillemonchicourt** [comment]
Je pense aussi que JDD est une info essentielle car elle permet de définir d'où vient la donnée.

**Comment by sig-pnrnm** [comment]
Il faudrait s'appuyer, je pense, sur le composant de Théo (https://github.com/PnX-SI/gn_module_validation/issues/4#issuecomment-380058489) : 
> , @TheoLechemia a mis en place un composant générique (DynamicForm) qui permet de lister dans un fichier de conf les champs que l'on souhaite utiliser ainsi que leur type (https://github.com/PnX-SI/GeoNature/blob/develop/contrib/occtax/frontend/app/occtax-map-list/filters-list.ts) et ça les propose dynamiquement dans l'interface.
> 
> Pour ne pas surcharger l'interface en les affichant tous, ils sont affichés dans une liste déroulante :

**Comment by camillemonchicourt** [comment]
Je ne pense pas que cela soit lié. 
Le composant DynamicForm permet d'afficher dynamiquement des champs dans un formulaire, pas dans une liste. 

Si je me souviens bien, ce composant est utilisé au niveau des filtres de la Synthèse pour les Filtres "Avancé (Taxonomie)".

Pour les champs affichés dans la liste et la possibilité de les customiser, il faut voir ce qui est possible. 
Car pour optimiser le chargement des résultats, dans la Synthèse, on a minimisé le nombre de champs renvoyés pour alléger le chargement. Les infos détaillées d'une occurrence sont chargés dans un second temps, en ajax, à la demande, quand l'utilisateur demande l'affichage des détails d'une occurrence.

@TheoLechemia aura peut-être des compléments sur ce sujet.

**Comment by TheoLechemia** [comment]
Oui le composant "dynamicForm" sert à générer des champs de formulaire de recherche dynamiquement. On l'utilise pour filtrer sur le champs de nomenclature du standard occurrence de taxon (Synthese et Occtax). ça permet d’alléger les formulaire tout en permettant de faire des recherches fines.

Pour la synthese, on a en effet simplifier au maximum la requête et le geojson renvoyé par l'API. Elle ne revoie que ces 5 colonnes  'id_synthese', 'date_min','observers', 'nom_valide','dataset_name', qui sont néanmoins paramétrable par l'administrateur qui peut mettre tout les champs présents de la table synthèse. Cependant dans la synthese, les nomenclature ne sont pas décodés, donc si on ajoute "id_nomenclature_life_stage" dans les colonnes que l'on veut afficher, on aura seulement le code et non le label de cette nomenclature.
On a donc un 2ème mécanisme qui permet de charger le détail de chaque observation en AJAX, qui lui renvoie toutes les infos de l'observation, avec toutes les colonnes de la synthese, des infos détaillés sur le JDD, la taxonomie, ainsi que les nomenclatures décodées. (voir https://github.com/PnX-SI/GeoNature/blob/master/backend/geonature/core/gn_synthese/routes.py#L147)

**Comment by gildeluermoz** [comment]
Sujet épineux mais effectivement important. Serait-il envisageable de construire la liste dynamiquement à partir d'une vue ? Ainsi on livre la vue avec les 5 colonnes actuelles et si qq'un veut changer, il réécrit la vue. @TheoLechemia ?

**Comment by TheoLechemia** [comment]
Oui bien-sur, on peut créer le tableau dynamiquement en fonction des champs renvoyé par l'API (que ce soit à partir d'une vue ou d'un table). C'est déjà le cas dans la Synthese ou on crée une vue très large, et on l'administrateur peut choisir les champs renvoyés dans le tableau.
