### ISSUE TITLE
Interaction Carte-Liste

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_validation#8]
Depuis la liste, zoomez sur la carte quand on clique à n'importe quel endroit d'une ligne, pas uniquement quand on la coche. 

Peut-être même que seule la coche ne zoome pas sur l'objet.

**Comment by sig-pnrnm** [comment]
Il semble que si l'on sélectionne plusieurs lignes, la carte ne zoome que sur la 1ère donnée sélectionnée.
Il faudrait que la Bbox s'adapte à l'ensemble de la sélection

**Comment by camillemonchicourt** [comment]
Fait et le zoom s'adapte à la BBOX des données sélectionnées.
