### ISSUE TITLE
Bouton TOUT SELECTIONNER

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_validation#9]
Ajouter un bouton permettant de sélectionner toutes les occurrences listées.

**Comment by camillemonchicourt** [comment]
Voir https://github.com/PnX-SI/gn_module_validation/commit/484a4914ee03fed2d3d71b63fde24633ae76d9f8

**Comment by orovellotti** [comment]
•	Message dans le PopUp vous avez sélectionné « 3000 données »
•	Pas de double check du nombre d’enregistrements validé
•	Problème de responsive sur cette Popup
•	Changer le bouton en "Envoyer" en "Enregistrer"

**Comment by camillemonchicourt** [comment]
Fait
